# 1.- CONSTRUIR LA IMAGEN DOCKER EN UN CONTENEDOR LIMPIO PARA ASEGURAR QUE EL AMBIENTE SE PUEDE RECREAR SIN PROBLEMAS
FROM node:14-alpine
LABEL version="1.0"
LABEL maintainer="barahonachrism@yahoo.es"

#DIRECTORIO DONDE VAMOS A COMPILAR TODO EL PROYECTO
WORKDIR /app
#COPIAR TODOS LOS MICROFRONTENDS A LA CARPETA /app DEL CONTENEDOR
COPY . .

RUN apk update && apk add curl

# CONSTRUIR EL PROYECTO CONTENEDOR DE LA APLICACION
RUN npm install

CMD [ "npm", "start" ]